titanium.platform=/Users/brian//Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android
android.platform=/Users/brian//Library/Android/sdk/platforms/android-22
google.apis=/Users/brian//Library/Android/sdk/add-ons/addon-google_apis-google-22
android.ndk=/Users/brian//Library/Android/ndk